<?xml version="1.0"?>
<package format="3">
  <name>cv_hw2</name>
  <version>0.1.0</version>
  <description>Vision HW2 - cone position detection with HSV slider Qt GUI</description>
  <maintainer email="lkh060320@gmail.com">lkh</maintainer>
  <author>lkh</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
